"""phase3_place_knowledge_sync

Revision ID: 5a15bef6f942
Revises: 816b502eadfd
Create Date: 2026-06-12 14:20:45.754672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a15bef6f942'
down_revision: Union[str, None] = '816b502eadfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
