from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816b502eadfd'
down_revision: Union[str, None] = 'bb7a81bae21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_knowledge_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('sync_status', sa.String(length=10), nullable=False),
    sa.Column('vector_count', sa.Integer(), nullable=True),
    sa.Column('pinecone_namespace', sa.String(length=300), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_knowledge_sync_id'), 'place_knowledge_sync', ['id'], unique=False)
    op.create_index(op.f('ix_place_knowledge_sync_place_id'), 'place_knowledge_sync', ['place_id'], unique=True)
    op.create_index(op.f('ix_place_knowledge_sync_sync_status'), 'place_knowledge_sync', ['sync_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_knowledge_sync_sync_status'), table_name='place_knowledge_sync')
    op.drop_index(op.f('ix_place_knowledge_sync_place_id'), table_name='place_knowledge_sync')
    op.drop_index(op.f('ix_place_knowledge_sync_id'), table_name='place_knowledge_sync')
    op.drop_table('place_knowledge_sync')
    # ### end Alembic commands ###
