"""add_payment_transactions_table

Revision ID: 8cf5fbf57966
Revises: 20260629000000
Create Date: 2026-06-30 14:36:03.704899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cf5fbf57966'
down_revision: Union[str, None] = '20260629000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_client_secret', sa.String(length=255), nullable=True),
    sa.Column('amount_inr', sa.Integer(), nullable=False, comment='Amount in INR (e.g. 150)'),
    sa.Column('amount_paise', sa.Integer(), nullable=False, comment='Amount in paise (e.g. 15000 for ₹150)'),
    sa.Column('credits_purchased', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_status'), 'payment_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_stripe_payment_intent_id'), 'payment_transactions', ['stripe_payment_intent_id'], unique=True)
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    
    # Drop indexes and tables conditionally using PostgreSQL IF EXISTS
    op.execute('DROP INDEX IF EXISTS ix_trip_places_id')
    op.execute('DROP INDEX IF EXISTS ix_trip_places_place_id')
    op.execute('DROP INDEX IF EXISTS ix_trip_places_trip_id')
    op.execute('DROP TABLE IF EXISTS trip_places')
    op.execute('DROP INDEX IF EXISTS ix_collection_places_collection_id')
    op.execute('DROP INDEX IF EXISTS ix_collection_places_id')
    op.execute('DROP INDEX IF EXISTS ix_collection_places_place_id')
    op.execute('DROP TABLE IF EXISTS collection_places')
    op.execute('DROP INDEX IF EXISTS ix_place_collections_id')
    op.execute('DROP INDEX IF EXISTS ix_place_collections_share_code')
    op.execute('DROP INDEX IF EXISTS ix_place_collections_user_id')
    op.execute('DROP TABLE IF EXISTS place_collections')
    op.execute('DROP INDEX IF EXISTS ix_place_alerts_active_location')
    op.execute('DROP INDEX IF EXISTS ix_place_alerts_id')
    op.execute('DROP INDEX IF EXISTS ix_place_alerts_place_id')
    op.execute('DROP INDEX IF EXISTS ix_place_alerts_user_id')
    op.execute('DROP TABLE IF EXISTS place_alerts')
    op.execute('DROP INDEX IF EXISTS ix_user_trips_id')
    op.execute('DROP INDEX IF EXISTS ix_user_trips_user_id')
    op.execute('DROP TABLE IF EXISTS user_trips')
    
    op.alter_column('place_details', 'extended_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Extended data from Google Places API (parking, payment, dining, services, etc.) + enrichment from Wikipedia and OpenStreetMap.',
               existing_nullable=True)
    op.drop_constraint(op.f('fk_place_qa_sessions_user_id'), 'place_qa_sessions', type_='foreignkey')
    op.alter_column('place_visit_logs', 'rating_given',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment="User's personal rating 1-5 (supports decimal values)",
               existing_nullable=True)
    op.alter_column('place_visit_logs', 'review_text',
               existing_type=sa.TEXT(),
               comment="User's personal notes/review",
               existing_nullable=True)
    op.alter_column('place_visit_logs', 'with_whom',
               existing_type=sa.VARCHAR(length=100),
               comment="Context: 'family', 'friends', 'solo', 'partner'",
               existing_nullable=True)
    op.alter_column('place_visit_logs', 'mood',
               existing_type=sa.VARCHAR(length=50),
               comment="Feeling: 'romantic', 'fun', 'quiet', 'adventurous'",
               existing_nullable=True)
    op.drop_index(op.f('ix_place_visit_logs_primary_type'), table_name='place_visit_logs')
    op.alter_column('user_saved_places', 'notes',
               existing_type=sa.TEXT(),
               comment="User's personal note about this place",
               existing_nullable=True)
    op.alter_column('user_saved_places', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='e.g. ["want_to_visit", "favorite", "recommended"]',
               existing_nullable=True)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               comment='True after OTP verification.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Set to False to deactivate an account.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'credits',
               existing_type=sa.INTEGER(),
               comment='Credit balance. Deducted by AI chat and Place Q&A.',
               existing_nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment='bcrypt hash. Set at account creation.')
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(length=20),
               comment="'local' for all users.",
               existing_nullable=False,
               existing_server_default=sa.text("'clerk'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="'local' for all users.",
               existing_nullable=False,
               existing_server_default=sa.text("'clerk'::character varying"))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment=None,
               existing_comment='bcrypt hash. Set at account creation.')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'credits',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Credit balance. Deducted by AI chat and Place Q&A.',
               existing_nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Set to False to deactivate an account.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True after OTP verification.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_saved_places', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='e.g. ["want_to_visit", "favorite", "recommended"]',
               existing_nullable=True)
    op.alter_column('user_saved_places', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="User's personal note about this place",
               existing_nullable=True)
    op.create_index(op.f('ix_place_visit_logs_primary_type'), 'place_visit_logs', ['primary_type'], unique=False)
    op.alter_column('place_visit_logs', 'mood',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Feeling: 'romantic', 'fun', 'quiet', 'adventurous'",
               existing_nullable=True)
    op.alter_column('place_visit_logs', 'with_whom',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Context: 'family', 'friends', 'solo', 'partner'",
               existing_nullable=True)
    op.alter_column('place_visit_logs', 'review_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="User's personal notes/review",
               existing_nullable=True)
    op.alter_column('place_visit_logs', 'rating_given',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment="User's personal rating 1-5 (supports decimal values)",
               existing_nullable=True)
    op.create_foreign_key(op.f('fk_place_qa_sessions_user_id'), 'place_qa_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('place_details', 'extended_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Extended data from Google Places API (parking, payment, dining, services, etc.) + enrichment from Wikipedia and OpenStreetMap.',
               existing_nullable=True)
    op.create_table('user_trips',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('destination_city', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('destination_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('destination_lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_places', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_trips_pkey'))
    )
    op.create_index(op.f('ix_user_trips_user_id'), 'user_trips', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_trips_id'), 'user_trips', ['id'], unique=False)
    op.create_table('place_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('place_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('formatted_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('radius_meters', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('100.0'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('remind_on_approach', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_triggered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('trigger_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('place_alerts_pkey'))
    )
    op.create_index(op.f('ix_place_alerts_user_id'), 'place_alerts', ['user_id'], unique=False)
    op.create_index(op.f('ix_place_alerts_place_id'), 'place_alerts', ['place_id'], unique=False)
    op.create_index(op.f('ix_place_alerts_id'), 'place_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_place_alerts_active_location'), 'place_alerts', ['is_active', 'latitude', 'longitude'], unique=False, postgresql_where='((is_active = true) AND (latitude IS NOT NULL) AND (longitude IS NOT NULL))')
    op.create_table('place_collections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cover_place_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cover_photo_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_collaborative', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('share_code', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('place_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('place_collections_pkey'))
    )
    op.create_index(op.f('ix_place_collections_user_id'), 'place_collections', ['user_id'], unique=False)
    op.create_index(op.f('ix_place_collections_share_code'), 'place_collections', ['share_code'], unique=True)
    op.create_index(op.f('ix_place_collections_id'), 'place_collections', ['id'], unique=False)
    op.create_table('collection_places',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('place_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('formatted_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rank_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['place_collections.id'], name=op.f('collection_places_collection_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_places_pkey'))
    )
    op.create_index(op.f('ix_collection_places_place_id'), 'collection_places', ['place_id'], unique=False)
    op.create_index(op.f('ix_collection_places_id'), 'collection_places', ['id'], unique=False)
    op.create_index(op.f('ix_collection_places_collection_id'), 'collection_places', ['collection_id'], unique=False)
    op.create_table('trip_places',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('place_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('formatted_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('photo_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('day_number', sa.Integer(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('visit_order', sa.Integer(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['user_trips.id'], name=op.f('trip_places_trip_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('trip_places_pkey'))
    )
    op.create_index(op.f('ix_trip_places_trip_id'), 'trip_places', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_places_place_id'), 'trip_places', ['place_id'], unique=False)
    op.create_index(op.f('ix_trip_places_id'), 'trip_places', ['id'], unique=False)
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_stripe_payment_intent_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    # ### end Alembic commands ###
