from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb7a81bae21d'
down_revision: Union[str, None] = '9b038a4ff5e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=500), nullable=True),
    sa.Column('formatted_address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('primary_type', sa.String(length=100), nullable=True),
    sa.Column('types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('international_phone_number', sa.String(length=50), nullable=True),
    sa.Column('national_phone_number', sa.String(length=50), nullable=True),
    sa.Column('website_uri', sa.Text(), nullable=True),
    sa.Column('google_maps_uri', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('user_rating_count', sa.Integer(), nullable=True),
    sa.Column('business_status', sa.String(length=50), nullable=True),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('open_now', sa.Boolean(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviews', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_level', sa.String(length=30), nullable=True),
    sa.Column('wheelchair_accessible_entrance', sa.Boolean(), nullable=True),
    sa.Column('editorial_summary', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('knowledge_synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_details_id'), 'place_details', ['id'], unique=False)
    op.create_index(op.f('ix_place_details_place_id'), 'place_details', ['place_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_details_place_id'), table_name='place_details')
    op.drop_index(op.f('ix_place_details_id'), table_name='place_details')
    op.drop_table('place_details')
    # ### end Alembic commands ###
