from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb3b8c851c9d'
down_revision: Union[str, None] = '816b502eadfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('knowledge_available', sa.Boolean(), nullable=False),
    sa.Column('pinecone_matches', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_questions_created_at'), 'place_questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_place_questions_id'), 'place_questions', ['id'], unique=False)
    op.create_index(op.f('ix_place_questions_place_id'), 'place_questions', ['place_id'], unique=False)
    op.create_index(op.f('ix_place_questions_user_id'), 'place_questions', ['user_id'], unique=False)
    op.create_table('place_answer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('answer_source', sa.String(length=20), nullable=False),
    sa.Column('grounding_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_tokens', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['place_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_answer_logs_id'), 'place_answer_logs', ['id'], unique=False)
    op.create_index(op.f('ix_place_answer_logs_place_id'), 'place_answer_logs', ['place_id'], unique=False)
    op.create_index(op.f('ix_place_answer_logs_question_id'), 'place_answer_logs', ['question_id'], unique=False)
    op.create_index(op.f('ix_place_answer_logs_user_id'), 'place_answer_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_answer_logs_user_id'), table_name='place_answer_logs')
    op.drop_index(op.f('ix_place_answer_logs_question_id'), table_name='place_answer_logs')
    op.drop_index(op.f('ix_place_answer_logs_place_id'), table_name='place_answer_logs')
    op.drop_index(op.f('ix_place_answer_logs_id'), table_name='place_answer_logs')
    op.drop_table('place_answer_logs')
    op.drop_index(op.f('ix_place_questions_user_id'), table_name='place_questions')
    op.drop_index(op.f('ix_place_questions_place_id'), table_name='place_questions')
    op.drop_index(op.f('ix_place_questions_id'), table_name='place_questions')
    op.drop_index(op.f('ix_place_questions_created_at'), table_name='place_questions')
    op.drop_table('place_questions')
    # ### end Alembic commands ###
